# Generated by Django 5.2.6 on 2025-09-25 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('GHS', 'Ghana Cedi'), ('KES', 'Kenyan Shilling')], default='NGN', max_length=3)),
                ('lease_term_preference', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('2_years', '2 Years')], max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('known_issues', models.TextField(blank=True, null=True)),
                ('house_rules', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_owner_or_representative', models.BooleanField(default=False)),
                ('details_accurate', models.BooleanField(default=False)),
                ('responsible_for_fraud', models.BooleanField(default=False)),
                ('allow_escrow', models.BooleanField(default=False)),
                ('signature', models.CharField(blank=True, max_length=100, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_for_review', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listings.propertydraft')),
            ],
        ),
    ]
