# Generated by Django 5.2.6 on 2025-10-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydraft',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertydraft',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('duplex', 'Duplex'), ('bungalow', 'Bungalow'), ('terraced_house', 'Terraced House'), ('mansion', 'Mansion'), ('mini_flat', 'Mini Flat'), ('self_contain', 'Self Contain')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertydraft',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
