# Generated by Django 5.2.6 on 2025-11-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bank_verified',
            field=models.BooleanField(default=False, help_text='Whether the bank details have been verified'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_account_name',
            field=models.CharField(blank=True, help_text='Account name of the property owner', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_account_number',
            field=models.CharField(blank=True, help_text='Account number of the property owner', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_bank_name',
            field=models.CharField(blank=True, help_text='Bank name of the property owner', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertydraft',
            name='bank_verified',
            field=models.BooleanField(default=False, help_text='Whether the bank details have been verified'),
        ),
        migrations.AddField(
            model_name='propertydraft',
            name='owner_account_name',
            field=models.CharField(blank=True, help_text='Account name of the property owner', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertydraft',
            name='owner_account_number',
            field=models.CharField(blank=True, help_text='Account number of the property owner', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertydraft',
            name='owner_bank_name',
            field=models.CharField(blank=True, help_text='Bank name of the property owner', max_length=100, null=True),
        ),
    ]
