# Generated by Django 5.2.6 on 2025-10-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotellisting',
            name='agrees_to_escrow_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotellisting',
            name='assume_responsibility_for_fraud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotellisting',
            name='details_accurate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotellisting',
            name='digital_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotellisting',
            name='is_owner_or_representative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotellisting',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
