# Generated by Django 5.2.6 on 2025-10-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotellisting_agrees_to_escrow_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotellisting',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
