# Generated by Django 5.2.6 on 2025-10-15 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPropertyDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_name', models.CharField(max_length=200)),
                ('landlord_phone', models.CharField(max_length=15)),
                ('landlord_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('GHS', 'Ghana Cedi'), ('KES', 'Kenyan Shilling')], default='NGN', max_length=3)),
                ('lease_term_preference', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('2_years', '2 Years')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('known_issues', models.TextField(blank=True, null=True)),
                ('house_rules', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('duplex', 'Duplex'), ('bungalow', 'Bungalow'), ('terraced_house', 'Terraced House'), ('mansion', 'Mansion'), ('mini_flat', 'Mini Flat'), ('self_contain', 'Self Contain')], max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('is_authorised_to_list', models.BooleanField(default=False)),
                ('details_accurate', models.BooleanField(default=False)),
                ('assume_responsibility_for_fraud', models.BooleanField(default=False)),
                ('agrees_to_escrow_process', models.BooleanField(default=False)),
                ('digital_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_for_review', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Property Draft',
                'verbose_name_plural': 'Agent Property Drafts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agent_listings.agentpropertydraft')),
            ],
            options={
                'verbose_name': 'Agent-Submitted Property',
                'verbose_name_plural': 'Agent-Submitted Properties',
            },
        ),
    ]
