# Generated by Django 5.2.6 on 2025-11-07 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeasePayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('listing_type', models.CharField(choices=[('landlord_listing', 'Landlord Listing'), ('agent_listing', 'Agent Listing')], max_length=20)),
                ('listing_id', models.IntegerField()),
                ('amount_paid_ngn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('security_deposit', 'Security Deposit'), ('first_month_rent', 'First Month Rent'), ('last_month_rent', 'Last Month Rent'), ('booking_fee', 'Booking Fee')], max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('transaction_ref', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord_or_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_payments_received', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_payments_initiated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
