# Generated by Django 5.2.6 on 2025-11-07 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('listing_type', models.CharField(choices=[('landlord_listing', 'Landlord Listing'), ('agent_listing', 'Agent Listing')], max_length=20)),
                ('listing_id', models.IntegerField()),
                ('status', models.CharField(choices=[('saved', 'Saved (Not Paid)'), ('paid_pending_confirmation', 'Paid, Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='saved', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='transactions.leasepayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
