# Generated by Django 5.2.6 on 2025-11-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='listing_type',
            field=models.CharField(choices=[('landlord_listing', 'Landlord Listing'), ('agent_listing', 'Agent Listing'), ('hotel_listing', 'Hotel Listing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leasepayment',
            name='listing_type',
            field=models.CharField(choices=[('landlord_listing', 'Landlord Listing'), ('agent_listing', 'Agent Listing'), ('hotel_listing', 'Hotel Listing')], max_length=20),
        ),
    ]
