# Generated by Django 5.2.6 on 2025-11-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_booking_listing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='initial_amount_paid_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('security_deposit', 'Security Deposit'), ('first_month_rent', 'First Month Rent'), ('booking_fee', 'Booking Fee'), ('full_rent', 'Full Rent'), ('hotel_stay', 'Hotel Stay')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Requested'), ('processed', 'Processed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='release_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('released', 'Released')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('paid_pending_confirmation', 'Paid - Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('released', 'Funds Released')], default='saved', max_length=25),
        ),
    ]
